### ISSUE TITLE
[BUG]: Error trying to run LLama2.mojo

### ISSUE THREAD

**Issue by 1997MarsRover** [modularml/mojo#1169]
### Bug description

I encountered an issue while running the mojo tool with the following command:

```bash
mojo llama2.mojo stories15M.bin -s 100 -n 256 -t 0.5 -i "Mojo is a language"
```
Error Message:

```yaml
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable

[1101:1101:20231027,140843.319764:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[1101:1101:20231027,140843.320803:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
[1101:1102:20231027,141028.006443:ERROR directory_reader_posix.cc:42] opendir /home/mars_rover/.modular/crashdb/attachments/ec513a01-ad90-4f30-96ca-7a3dea3d901d: No such file or directory (2)
```
**Expected Behavior.**
I expected the mojo tool to execute the command without errors and produce the intended output.
**Output expected**
```yaml
num hardware threads:  6
SIMD vector width:  16
checkpoint size:  60816028 [ 57 MB ]
n layers:  6
vocab size:  32000
Mojo is a language that people like to talk. Hephones are very different from other people. He has a big book with many pictures and words. He likes to look at the pictures and learn new things.
One day, Mojo was playing with his friends in the park. They were running and laughing and having fun. Mojo told them about his book and his friends. They listened and looked at the pictures. Then, they saw a picture of a big, scary monster. They were very scared and ran away.
Mojo was sad that his book was gone. He told his friends about the monster and they all felt very sad. Mojo's friends tried to make him feel better, but nothing worked. Mojo never learned his language again.
achieved tok/s:  440.21739130434781
```

### Steps to reproduce

1. Run the following command in a terminal:
```bash
mojo llama2.mojo stories15M.bin -s 100 -n 256 -t 0.5 -i "Mojo is a language"
```

### System information

```shell
- WSL:Ubuntu
- mojo 0.3.0 (f64f9601)
- modular 0.1.4 (6b54d308)
```
