### ISSUE TITLE
[BUG] mojo run and mojo test show different behaviour regarding library search path

### ISSUE THREAD

**Issue by sbrunk** [modularml/mojo#3608]
### Bug description

In a Magic environment, `mojo run` and `mojo test` behave differently regarding the library search path. `mojo run` seems to find libraries in `.magic/envs/default/lib` while `mojo test` does not.

@zbowlin [suggested on Discord](https://discord.com/channels/1087530497313357884/1267269207372988597/1290836676108746826) that they *should* behave the same.

### Steps to reproduce

```shell
magic init --format mojoproject
magic add libduckdb
magic shell
```

Create a file `test_example.mojo`

```mojo
from sys.ffi import DLHandle
from sys import os_is_macos

fn load_lib() -> DLHandle:
    @parameter
    if os_is_macos():
        return DLHandle("libduckdb.dylib")
    else:
        return DLHandle("libduckdb.so")

def main():
    _ = load_lib()

def test_example():
    _ = load_lib()
```

```shell
mojo run test_example.mojo # ok
magic test test_example.mojo # fails to load the library

dlopen failed: dlopen(libduckdb.dylib, 0x000A): tried: 'libduckdb.dylib' (no such file), '/usr/lib/libduckdb.dylib' (no such file, not in dyld cache), 'libduckdb.dylib' (no such file)
```

### System information

- What OS did you do install Mojo on ? macOS 14
`mojo -v`: mojo 24.5.0 (e8aacb95)

**Comment by sbrunk** [comment]
Meanwhile, here's a workaround that works for me with Magic:

`mojoproject.toml`
```toml
[tasks]
test = { cmd = "mojo test -I $PIXI_PROJECT_ROOT", env = { DYLD_LIBRARY_PATH = "$CONDA_PREFIX/lib", LD_LIBRARY_PATH = "$CONDA_PREFIX/lib" }, cwd = "test" }
```
Then we can just run `magic run test`
